# Site
name: "LifeWorks Design Organization"
description: "Where you can come to see the weekly newsletters."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
email: "andrew.kelly@lifeworks.com"
mailchimp-list: ""

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  andrew:
    name: Andrew Kelly
    site: https://lifeworks.com/
    avatar: /assets/images/andrew-headshot.jpg
    bio: "The head of the LifeWorks Enterprise Design Organization."
    email: andrew.kelly@lifeworks.com
    twitter: https://twitter.com/andrewkelly


# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Paginate
paginate: 10
